name: restaurant_availability_system
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.3.6
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  intl: ^0.19.0
  uuid: ^4.3.3
  fl_chart: ^0.63.0
  flutter_local_notifications: ^14.1.5
  path_provider: ^2.1.2
  shared_preferences: ^2.2.3
  cached_network_image: ^3.3.1
  firebase_messaging: ^14.7.15
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/lang/